version: "3.7"
services: 
    application:
        image: vedantkdesai/k8s-spring-boot-application:v1.0.0
        container_name: application
        restart: unless-stopped
        ports : 
            - 8080:8080
        networks: 
            - app-network
networks:
    app-network: 
        