version: "3.7"
services: 
    application:
        image: k8sapplication:v1
        container_name: application
        restart: unless-stopped
        ports : 
            - 8080:8080
        networks: 
            - app-network
networks:
    app-network: 
        